/**
 * Pulumi program for All the Blame preview hosting on Cloudflare.
 *
 * Resources:
 *   - R2 bucket "pulumi-state"      self-hosted state backend (also stored here)
 *   - R2 bucket "vscode-web-base"   versioned vscode-web tarball extracts,
 *                                    shared across every PR preview. Public
 *                                    read so the Pages sites can fetch from
 *                                    the bucket directly.
 *   - Cloudflare Pages project      connected to the GitHub repo. Builds
 *                                    every PR, posts the preview URL as a
 *                                    comment. Not Pulumi-managed for the
 *                                    connection step (that requires dashboard
 *                                    OAuth) — we define the project here for
 *                                    configuration but the first deploy is
 *                                    bootstrapped via `wrangler pages
 *                                    project create` or the dashboard. See
 *                                    infra/README.md.
 *
 * OIDC trust configuration for GitHub Actions is set up in the Cloudflare
 * dashboard (one-time) — it's not a Pulumi resource because the Cloudflare
 * terraform/pulumi provider doesn't expose it as of Apr 2026. It's not an
 * operational issue since the trust is configured once and never changes.
 */

import * as cloudflare from "@pulumi/cloudflare";
import * as pulumi from "@pulumi/pulumi";

const cfg = new pulumi.Config();
const cfCfg = new pulumi.Config("cloudflare");
const accountId = cfCfg.require("accountId");
const githubRepo = cfg.require("githubRepo");
const pagesProjectName = cfg.require("pagesProjectName");

// --- R2 buckets ---

/**
 * State backend for Pulumi itself. Small, private, long-lived.
 * Created here so the infra repo self-describes where state lives —
 * but note: on first run this bucket has to exist already before
 * `pulumi login s3://pulumi-state?…` can read state from it. See
 * infra/README.md for the bootstrap.
 */
const stateBucket = new cloudflare.R2Bucket("pulumi-state", {
	accountId,
	name: "pulumi-state",
	location: "wnam",
});

/**
 * Shared vscode-web base. Gets one sub-prefix per vscode-web version:
 *     vscode-web-base/<commit-sha>/…
 * Per-PR previews reference
 *     https://<accountId>.r2.cloudflarestorage.com/vscode-web-base/<sha>
 * as their `WORKBENCH_WEB_BASE_URL`, so the 115 MB payload is
 * downloaded once per viewer and cached via Cloudflare's edge.
 */
const baseBucket = new cloudflare.R2Bucket("vscode-web-base", {
	accountId,
	name: "vscode-web-base",
	location: "wnam",
});

// Public read access so browsers can GET without signed URLs. The
// contents are public artifacts of VS Code's own web release anyway.
const _baseBucketPublic = new cloudflare.R2BucketManagedDomain(
	"vscode-web-base-public",
	{
		accountId,
		bucketName: baseBucket.name,
		enabled: true,
		domain: pulumi.interpolate`${baseBucket.name}.r2.dev`, // auto-assigned
	},
);

// CORS: allow any origin so Pages-hosted previews (on any hostname,
// including per-PR `<hash>.all-the-blame-preview.pages.dev`) can fetch
// the workbench JS/CSS/wasm.
const _baseBucketCors = new cloudflare.R2BucketCors("vscode-web-base-cors", {
	accountId,
	bucketName: baseBucket.name,
	rules: [
		{
			allowed: {
				methods: ["GET", "HEAD"],
				origins: ["*"],
			},
			exposeHeaders: ["ETag"],
			maxAgeSeconds: 86400,
		},
	],
});

// --- Cloudflare Pages project ---
//
// The GitHub OAuth connection for Pages is NOT Pulumi-managed.
// Cloudflare's provider can define the project; the GitHub
// integration is established separately in the dashboard
// (connect via Pages → Overview → Connect to GitHub). Once
// connected, every push/PR triggers a build automatically.
const pagesProject = new cloudflare.PagesProject(pagesProjectName, {
	accountId,
	name: pagesProjectName,
	productionBranch: "main",
	buildConfig: {
		buildCommand:
			"pnpm install --frozen-lockfile && pnpm run build && node scripts/build-vscode-web-preview.mjs --base-url=https://vscode-web-base.r2.dev",
		destinationDir: "preview-vscode-web",
		rootDir: "",
	},
	deploymentConfigs: {
		preview: {
			environmentVariables: {
				NODE_VERSION: "24",
			},
			// Each PR gets its own environment. Per-PR URLs are
			// auto-generated by Cloudflare Pages; we just need to enable
			// the preview environment.
		},
		production: {
			environmentVariables: {
				NODE_VERSION: "24",
			},
		},
	},
	source: {
		type: "github",
		config: {
			owner: githubRepo.split("/")[0],
			repoName: githubRepo.split("/")[1],
			productionBranch: "main",
			prCommentsEnabled: true,
			deploymentsEnabled: true,
			productionDeploymentEnabled: true,
			previewDeploymentSetting: "all",
			previewBranchIncludes: ["*"],
			previewBranchExcludes: [],
		},
	},
});

// --- Outputs (what the rest of the repo needs to know) ---

export const stateBucketName = stateBucket.name;
export const baseBucketName = baseBucket.name;
export const basePublicUrl = pulumi.interpolate`https://${baseBucket.name}.r2.dev`;
export const previewProductionUrl = pulumi.interpolate`https://${pagesProjectName}.pages.dev`;
export const previewProjectName = pagesProject.name;
