# Stolen from https://github.com/HaaLeo/publish-vscode-extension#readme
name: Deploy Extension
permissions:
    contents: read

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
              with:
                  node-version: 24
            - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
            - run: pnpm install --frozen-lockfile
            - name: Publish to VS Code Marketplace
              uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # 2.0.0 release
              id: publishToVSCMarketplace
              with:
                  pat: ${{ secrets.VSCE_PAT }}
                  registryUrl: https://marketplace.visualstudio.com
            - name: Publish to Open VSX Registry
              uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # 2.0.0 release
              id: publishToOpenVSX
              with:
                  pat: ${{ secrets.OPEN_VSX_TOKEN }}
